### PR TITLE
Fix fparselncheck on FreeBSD

### LINKED ISSUE #22: mg 6.5 fails to build on FreeBSD 13.0
```
fparseln.c:78:1: error: static declaration of 'fgetln' follows non-static declaration
fgetln(FILE *fp, size_t *len)
^
/usr/include/stdio.h:385:7: note: previous declaration is here
char    *fgetln(FILE *, size_t *);
         ^
1 error generated.
*** [fparseln.o] Error code 1
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #22

### CODE REVIEW

**Comment by ibara** [comment]
Thanks.
