### ISSUE TITLE
mg 6.5 fails to build on FreeBSD 13.0

### ISSUE THREAD

**Issue by ghost** [ibara/mg#22]
```
fparseln.c:78:1: error: static declaration of 'fgetln' follows non-static declaration
fgetln(FILE *fp, size_t *len)
^
/usr/include/stdio.h:385:7: note: previous declaration is here
char    *fgetln(FILE *, size_t *);
         ^
1 error generated.
*** [fparseln.o] Error code 1
```

**Comment by ghost** [comment]
The fparseln configure check fails with

```
checking for fparseln... conftest.c:7:10: error: 'util.h' file not found with <angled> include; use "quotes" instead
#include <util.h>
         ^~~~~~~~
         "util.h"
1 error generated.
no
```
